config/routes.rb
Rails.application.routes.draw do
  
  devise_for :authors

  resources :articles do
    resources :comments
  end

  root :to => 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_taggable_on :tags
  has_attached_file :cover_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :cover_image, :content_type => /\Aimage\/.*\Z/
  has_many :comments, dependent: :destroy

  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # attr_accessible :title, :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :authenticate_author!, except: [:index, :show]

  def index
    articles = Article.all
    @articles = Kaminari.paginate_array(articles).page(params[:page]).per(10)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update_attributes(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :cover_image,:tag_list)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_filter :authenticate_author!, only: [:destroy]
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
   
  private
  
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  
  <%= f.file_field :cover_image %>
  
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div> 
  
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<%= paginate @articles %>
<% @articles.each do |article| %>
  <h4><%= link_to article.title, article %></h4>
  <p><%= article.text %></p>
  <p><b>Tags:</b>
    <% article.tag_list.each do |tag| %>
      <%= tag %>
    <% end %>
  </p>
  <% if author_signed_in? %>
    <p><%= link_to 'Edit', edit_article_path(article) %>
    <%= link_to 'Destroy', article_path(article),
            method: :delete,
            data: { confirm: 'Are you sure?' } %></p>
  <% end%>
<% end %>
<br>
<%= link_to 'New article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="row">
  <div class="col-md-9">
    <%= image_tag @article.cover_image.url if @article.cover_image.present? %>
  </div>

  <div class="col-md-3">
	<p>
	  <strong>Title:</strong>
	  <%= @article.title %>
	</p>

  <p>
	  <strong>Text:</strong>
	  <%= @article.text %>
	</p>

  <h2>Comments</h2>
  <%= render @article.comments %>

  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>

  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Back', articles_path %>
  </div>
</div>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<% if author_signed_in? %>
  <p>
    <%= link_to 'Destroy Comment', [comment.article, comment],
	            method: :delete,
	            data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="container">
  	  <div id="user_nav">
  	    <% if author_signed_in? %>
  	      Logged in as <strong><%= current_author.email %></strong>.
  	      <%= link_to 'Edit profile', edit_author_registration_path %> |
  	      <%= link_to "Logout", destroy_author_session_path, method: :delete %>
  	    <% else %>
  	      <%= link_to "Sign up", new_author_registration_path %> |
  	      <%= link_to "Login", new_author_session_path %>
  	    <% end %>
  	  </div>

  	  <% flash.each do |name, msg| %>
  	    <%= content_tag :div, msg, id: "flash_#{name}" %>
  	  <% end %>

      <%= yield %>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </body>
</html>